export const LOGIN = 'LOGIN'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const LOGOUT = 'LOGOUT'

export const UPDATE_ALL_CATEGORY = 'UPDATE_ALL_CATEGORY'

export const ADD_TAG_GROUP_ITEM = 'ADD_TAG_GROUP_ITEM'
export const DELETE_TAG_GROUP_ITEM = 'DELETE_TAG_GROUP_ITEM'
export const UPDATE_TAG_GROUP_ITEM_NAME = 'UPDATE_TAG_GROUP_ITEM_NAME'
export const UPDATE_ALL_TAG_GROUP = 'UPDATE_ALL_TAG_GROUP'
export const UPDATE_TAG_GROUP_CREATE_TEXT = 'UPDATE_TAG_GROUP_CREATE_TEXT'

export const ADD_TAG_ITEM = 'ADD_TAG_ITEM'
export const DELETE_TAG_ITEM = 'DELETE_TAG_ITEM'
export const UPDATE_TAG_ITEM_NAME = 'UPDATE_TAG_ITEM_NAME'

export const UPDATE_ALL_SERVICE_TAG = 'UPDATE_ALL_SERVICE_TAG'
export const UPDATE_ALL_SERVICE_GROUP_TAG = 'UPDATE_ALL_SERVICE_GROUP_TAG'

export const ADD_CUSTOM_PAGE = 'ADD_CUSTOM_PAGE'
export const UPDATE_CUSTOM_PAGE = 'UPDATE_CUSTOM_PAGE'
export const DELETE_CUSTOM_PAGE = 'DELETE_CUSTOM_PAGE'
export const UPDATE_ALL_CUSTOM_PAGE = 'UPDATE_ALL_CUSTOM_PAGE'
export const UPDATE_ALL_CUSTOM_PAGE_DATA = 'UPDATE_ALL_CUSTOM_PAGE_DATA'
export const INIT_CUSTOM_PAGE_TITLE = 'INIT_CUSTOM_PAGE_TITLE'

